sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - cmake
      - doxygen
      - libboost1.65-dev

script:
  - mkdir build-debug-generators
  - cd build-debug-generators
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DGENERATORS=on
  - make
  - make test
  - cd ..
  - mkdir build-release-generators
  - cd build-release-generators
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DGENERATORS=on
  - make
  - make test
  - cd ..
  - mkdir build-release
  - cd build-release
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - make test
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build-release/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
