sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - cmake
      - doxygen

script:
  - mkdir build-release
  - cd build-release
  - cmake ..
  - make doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build-release/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
