name: Doxygen CI

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install requirements
        run: |
          apt install install doxygen
      - name: Create build directory
        run: mkdir build-debug-generators
      - name: Configure
        run: cd build-debug-generators && cmake .. -DCMAKE_BUILD_TYPE=Debug -DGENERATORS=on
      - name: Compile
        run: cd build-debug-generators && make
      - name: Test
        run: cd build-debug-generators && make test
      - name: Create documentation
        run: cd build-debug-generators && make doc
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
#          clean: false
      - name: Move and commit files
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/$GITHUB_REPOSITORY
          ls -l 
          #rm -rf d* && rm *.html && rm *.svg && rm *.map && rm *.md5 && rm *.png && rm *.js && rm *.css
#git add .
#          cp -rp ./build/html/* . && rm -rf ./build && ls -lah
#          git add .
          git commit -m "Documentation for $GITHUB_SHA" ||  true
          git push --force || true
